#!/usr/bin/env python3
"""Generate an AI-readable repository inventory with explicit GitHub URLs.

The output is navigation metadata only. It does not prove that a reader fetched,
read, validated, approved, or understood any listed file.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from urllib.parse import quote

DEFAULT_OUTPUT = Path("docs/ai-readable/repository-map.generated.md")
EXCLUDED_DIRECTORY_NAMES = {".git", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
EXCLUDED_FILE_NAMES = {".DS_Store"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."), help="repository root")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="output Markdown path")
    parser.add_argument(
        "--repository-url",
        default="https://github.com/YutoriKomeiji/responsibility-pathway-engineering",
        help="repository browser URL without a trailing slash",
    )
    parser.add_argument("--ref", default="main", help="Git ref used in generated browser links")
    return parser.parse_args()


def should_include(path: Path, root: Path, output: Path) -> bool:
    relative = path.relative_to(root)
    if path == output:
        return False
    if any(part in EXCLUDED_DIRECTORY_NAMES for part in relative.parts[:-1]):
        return False
    if path.name in EXCLUDED_FILE_NAMES:
        return False
    return path.is_file()


def browser_url(repository_url: str, ref: str, relative_path: Path) -> str:
    encoded = "/".join(quote(part) for part in relative_path.parts)
    return f"{repository_url.rstrip('/')}/blob/{quote(ref)}/{encoded}"


def render_map(root: Path, output: Path, repository_url: str, ref: str) -> str:
    files = sorted(
        path.relative_to(root)
        for path in root.rglob("*")
        if should_include(path, root, output)
    )

    grouped: dict[str, list[Path]] = {}
    for relative in files:
        group = relative.parts[0] if len(relative.parts) > 1 else "repository root"
        grouped.setdefault(group, []).append(relative)

    lines = [
        "# Generated Repository Map",
        "",
        "> Generated navigation metadata. Do not edit this file by hand.",
        "> Listed does not mean fetched, read, validated, approved, complete, or production-ready.",
        "",
        f"Repository: `{repository_url.rstrip('/')}`",
        f"Link ref: `{ref}`",
        f"Listed files: `{len(files)}`",
        "",
        "## Reading rule",
        "",
        "Fetch an exact file URL before summarizing its contents. Directory and file names are navigation hints only.",
        "",
    ]

    for group in sorted(grouped, key=lambda value: (value != "repository root", value.lower())):
        lines.extend([f"## {group}", ""])
        for relative in grouped[group]:
            url = browser_url(repository_url, ref, relative)
            lines.append(f"- [`{relative.as_posix()}`]({url})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    output = args.output if args.output.is_absolute() else root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_map(root, output, args.repository_url, args.ref), encoding="utf-8")
    print(f"generated {output.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
